spring:
  jackson:
    time-zone: Asia/Seoul
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.spl
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 347987644897-oknopga4cnbtkc9nb4f1pogu5i1dt3sa.apps.googleusercontent.com
#            clientId: ${G_CLIENT_ID}
            clientSecret: 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
#            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key:
#    secret: ${JWT_SECRET_KEY}
    secret: asdasdfawer23123efgsdfgsdfasdfgadfh
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420
  # for test #
#  access-token-expiration-minutes: 1
#  refresh-token-expiration-minutes: 2
