import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import RecoilRootWrapper from "@/app/_component/RecoilRootWrapper";
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children
}: {
    children: React.ReactNode
                                   }
) {
  const ComponentA = dynamic(() => import('@/app/_component/RecoilRootWrapper'),{ ssr: false })
  return (
    <html lang="en">
      <body className={inter.className}>
      <ComponentA>
          {children}
      </ComponentA>
      </body>
    </html>
  );
}
